const CHANGE_PROPERTY = 'CHANGE_PROPERTY';
const CREATE_TODO = 'CREATE_TODO';
const SELECT_TODO_TO_UPDATE = 'SELECT_TODO_TO_UPDATE';
const UPDATE_TODO = 'UPDATE_TODO';
const DELETE_TODO = 'DELETE_TODO';
const DELETE_ALL = 'DELETE_ALL';
const CLEAR_FORM = 'CLEAR_FORM';

export {CHANGE_PROPERTY, CREATE_TODO, SELECT_TODO_TO_UPDATE, UPDATE_TODO, DELETE_TODO, DELETE_ALL, CLEAR_FORM};
